version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  api:
    environment:
      API_PORT: 8080
      POSTGRES_DSN: "dbname=postgres user=postgres password=postgres host=db"
    build: ./api
    ports:
      - 8080:8080

